# keep this config in sync between dmd, druntime and phobos
with common_steps_template: &COMMON_STEPS_TEMPLATE
  run_script: |
    if [ "$OS_NAME" == "freebsd" ]; then pkg install -y bash; fi
    bash cirrusci.sh

environment:
  CIRRUS_CLONE_DEPTH: 50
  # for ci.sh:
  MODEL: 64
  DMD: dmd
  N: 4
  BRANCH: master
  OS_NAME: linux
  FULL_BUILD: true

# Linux
task:
  name: Ubuntu 16.04 $TASK_NAME_SUFFIX
  container:
    image: ubuntu:16.04
    cpu: 4
    memory: 8G
  timeout_in: 60m
  environment:
    matrix:
      - TASK_NAME_SUFFIX: x86, DMD (latest)
        MODEL: 32
      - TASK_NAME_SUFFIX: x86, DMD (bootstrap)
        MODEL: 32
        D_VERSION: 2.079.0
      - TASK_NAME_SUFFIX: x64, DMD (latest)
      - TASK_NAME_SUFFIX: x64, DMD (bootstrap)
        D_VERSION: 2.079.0
      - TASK_NAME_SUFFIX: x64, LDC
        DMD: ldc
      - TASK_NAME_SUFFIX: x64, GDC
        GDC_VERSION: 9
        DMD: gdmd-9
  << : *COMMON_STEPS_TEMPLATE

# Mac
task:
  name: macOS 10.15 x64, $TASK_NAME_SUFFIX
  osx_instance:
    image: catalina-xcode
  timeout_in: 60m
  environment:
    OS_NAME: darwin
    # override Cirrus default OS (`darwin`)
    OS: osx
    matrix:
      - TASK_NAME_SUFFIX: DMD (latest)
      - TASK_NAME_SUFFIX: DMD (bootstrap)
        # de-facto bootstrap version on OSX
        # See: https://forum.dlang.org/post/qfsgt2$1goc$1@digitalmars.com
        D_VERSION: 2.088.0
  << : *COMMON_STEPS_TEMPLATE

# FreeBSD
task:
  name: FreeBSD 12.1 x64, DMD (latest)
  freebsd_instance:
    image_family: freebsd-12-1
    cpu: 4
    memory: 8G
  timeout_in: 60m
  environment:
    OS_NAME: freebsd
  << : *COMMON_STEPS_TEMPLATE

task:
  name: FreeBSD 11.4 x64, DMD (bootstrap)
  freebsd_instance:
    image_family: freebsd-11-4
    cpu: 4
    memory: 8G
  timeout_in: 60m
  environment:
    OS_NAME: freebsd
    D_VERSION: 2.079.0
  << : *COMMON_STEPS_TEMPLATE
