recipe: &recipe
  working_directory: ~/dmd
  docker:
    - image: circleci/buildpack-deps:18.04
  steps:
    - checkout
    - run:
        command: ./.circleci/run.sh install-deps
        name: Install dependencies
    - run:
        # needs to be a separate step, s.t. `run.sh` gets updated too
        command: ./.circleci/run.sh setup-repos
        name: Merge with upstream + clone DRuntime & Phobos
    - run:
        command: ./.circleci/run.sh all
        name: Run all

version: 2
jobs:
  pic:
    <<: *recipe
  no_pic:
    <<: *recipe
    parallelism: 2

workflows:
  version: 2
  all:
    jobs:
      - pic
      - no_pic
