version: 2
jobs:
  no_pic:
    working_directory: ~/dmd
    docker:
      - image: circleci/node:4.8.2
    parallelism: 2
    steps:
      - checkout
      - run:
          command: ./.circleci/run.sh install-deps
          name: Install dependencies
      - run:
          command: ./.circleci/run.sh all
          name: Run all
  pic:
    working_directory: ~/dmd
    docker:
      - image: dlang2/dmd-circleci:2.078.0
    steps:
      - checkout
      - run:
          # this is needed to "fix" the Docker permission errors - see https://github.com/dlang/dmd/pull/7579
          command: sudo ls -l /dlang/dmd-2.078.0/linux && sudo ls -l /dlang/dmd-2.078.0/src
          name: Test Docker image
      - run:
          command: ./.circleci/run.sh all
workflows:
  version: 2
  all:
    jobs:
      - pic
      - no_pic
