# This file is just a reusable action that will automatically checkout DRuntime / Phobos with a
# branch.

name: Checkout DRuntime / Phobos

runs:
  using: "composite"
  steps:
  ##############################################
  # Find out which branch we need to check out #
  ##############################################
  - name: Determine base branch
    id: base_branch
    shell: bash
    run: |
      # For pull requests, base_ref will not be empty
      if [ ! -z ${{ github.base_ref }} ]; then
          echo "::set-output name=branch::${{ github.base_ref }}"
      # Otherwise, use whatever ref we have:
      # For branches this in the format 'refs/heads/<branch_name>',
      # and for tags it is refs/tags/<tag_name>.
      else
          echo "::set-output name=branch::${{ github.ref }}"
      fi
  - name: Checkout druntime
    uses: actions/checkout@v2
    with:
      path: druntime
      repository: dlang/druntime
      ref: ${{ steps.base_branch.outputs.branch }}
      persist-credentials: false
  - name: Checkout Phobos
    uses: actions/checkout@v2
    with:
      path: phobos
      repository: dlang/phobos
      ref: ${{ steps.base_branch.outputs.branch }}
      persist-credentials: false
